# Generated by Django 3.1.2 on 2021-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_rating', models.IntegerField(default='0')),
                ('movie_release_date', models.DateField()),
                ('movie_duration', models.IntegerField(default='0')),
                ('movie_description', models.CharField(max_length=100)),
            ],
        ),
    ]
