# Generated by Django 3.1.2 on 2021-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='movie_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
